### ISSUE TITLE
이미지 업로드용

### ISSUE THREAD

**Issue by taelee42** [Kraken-Addicts/HTTP-The-Definitive-Guide#10]
![Group 4 (1)](https://user-images.githubusercontent.com/55867479/93372632-1be18e00-f88f-11ea-846b-395ed27d27a2.png)

**Comment by hidaehyunlee** [comment]
![image](https://user-images.githubusercontent.com/37580034/96361349-dfd86c00-115f-11eb-8c22-35506617228c.png)
