### ISSUE TITLE
이미지 업로딩용

### ISSUE THREAD

**Issue by taelee42** [Kraken-Addicts/HTTP-The-Definitive-Guide#5]
![image](https://user-images.githubusercontent.com/55867479/92004376-1fe4ba80-ed7d-11ea-92e9-4f4a27768249.png)

**Comment by 365kim** [comment]
눈치게임 1

**Comment by hidaehyunlee** [comment]
눈치게임2

**Comment by taelee42** [comment]
눈치게임3
