### ISSUE TITLE
image upload

### ISSUE THREAD

**Issue by kunheeya** [Kraken-Addicts/HTTP-The-Definitive-Guide#6]
<img width="944" alt="ch17_cont" src="https://user-images.githubusercontent.com/57086195/92450684-b0e0e900-f1f6-11ea-88aa-168809972003.png">

**Comment by hidaehyunlee** [comment]
![image-20200916191243494](https://user-images.githubusercontent.com/37580034/93333348-26376400-f85e-11ea-8604-a755dfa85884.png)
